Revert "Try out pipeline stats"
This reverts commit e2eb2953bcb5e13e65d413b6f0a74e8d12cd573c.

Error:
> Run peter-evans/repository-dispatch@v1
>   with:
>     token: ***
>     event-type: trigger-stats
>     client-payload: {"pull_request": {"number": ""}}
>     repository: binkley/publishing-pipeline
> Error: Resource not accessible by integration